\set ON_ERROR_STOP on

-- Firecrawl's current API calls these PostgreSQL functions directly. They are
-- not included in the upstream self-host guide, so the community distribution
-- supplies standalone equivalents. Billing is a no-op and rate limits default
-- to an operator-owned unlimited policy rather than a Firecrawl Cloud plan.

CREATE OR REPLACE FUNCTION public.selfhost_unlimited_rate_limit_flags()
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
AS $function$
  SELECT jsonb_build_object(
    'rateLimitOverrides',
    jsonb_build_object(
      'crawl', 2147483647,
      'crawlStatus', 2147483647,
      'scrape', 2147483647,
      'scrapeAgentPreview', 2147483647,
      'preview', 2147483647,
      'search', 2147483647,
      'map', 2147483647,
      'extract', 2147483647,
      'extractStatus', 2147483647,
      'extractAgentPreview', 2147483647,
      'browser', 2147483647,
      'browserExecute', 2147483647,
      'browserReplay', 2147483647,
      'account', 2147483647,
      'supportAsk', 2147483647,
      'supportDocsSearch', 2147483647,
      'research', 2147483647,
      'developerSearch', 2147483647,
      'labs', 2147483647
    )
  )
$function$;

CREATE TABLE IF NOT EXISTS public.firecrawl_change_tracking_scrapes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id uuid NOT NULL,
  url text NOT NULL,
  job_id text NOT NULL,
  change_tracking_tag text,
  date_added timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS firecrawl_change_tracking_lookup_idx
  ON public.firecrawl_change_tracking_scrapes
    (team_id, url, change_tracking_tag, date_added DESC);

CREATE OR REPLACE FUNCTION public.auth_chunk_1(
  input_key text,
  input_credential_purpose text DEFAULT 'general'
)
RETURNS TABLE (
  api_key text,
  api_key_id bigint,
  team_id uuid,
  org_id uuid,
  flags jsonb,
  is_banned boolean
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
  SELECT
    k.key::text,
    k.id,
    t.id,
    t.org_id,
    public.selfhost_unlimited_rate_limit_flags(),
    COALESCE(t.banned, false)
  FROM public.api_keys k
  JOIN public.teams t ON t.id = k.team_id
  WHERE k.key::text = input_key
  LIMIT 1
$function$;

CREATE OR REPLACE FUNCTION public.auth_chunk_1_from_team(input_team text)
RETURNS TABLE (
  api_key text,
  api_key_id bigint,
  team_id uuid,
  org_id uuid,
  flags jsonb,
  is_banned boolean
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
  SELECT
    k.key::text,
    k.id,
    t.id,
    t.org_id,
    public.selfhost_unlimited_rate_limit_flags(),
    COALESCE(t.banned, false)
  FROM public.teams t
  LEFT JOIN LATERAL (
    SELECT ak.id, ak.key
    FROM public.api_keys ak
    WHERE ak.team_id = t.id
    ORDER BY ak.id
    LIMIT 1
  ) k ON true
  WHERE t.id = input_team::uuid
  LIMIT 1
$function$;

CREATE OR REPLACE FUNCTION public.bill_team_7(
  _team_id uuid,
  sub_id text,
  credits numeric,
  i_api_key_id bigint,
  is_extract_param boolean
)
RETURNS TABLE (api_key text)
LANGUAGE sql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
  SELECT k.key::text
  FROM public.api_keys k
  WHERE k.team_id = _team_id
    AND (i_api_key_id IS NULL OR k.id = i_api_key_id)
  ORDER BY k.id
  LIMIT 1
$function$;

CREATE OR REPLACE FUNCTION public.credits_billed_by_crawl_id_2(i_crawl_id uuid)
RETURNS TABLE (credits_billed bigint)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $function$
  SELECT COALESCE((
    SELECT c.credits_cost::bigint
    FROM public.crawls c
    WHERE c.id = i_crawl_id
    LIMIT 1
  ), 0::bigint)
$function$;

CREATE OR REPLACE FUNCTION public.change_tracking_insert_scrape(
  p_team_id uuid,
  p_url text,
  p_job_id text,
  p_change_tracking_tag text,
  p_date_added timestamptz
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
SET search_path = public, pg_temp
AS $function$
DECLARE
  inserted_id bigint;
BEGIN
  INSERT INTO public.firecrawl_change_tracking_scrapes (
    team_id, url, job_id, change_tracking_tag, date_added
  ) VALUES (
    p_team_id, p_url, p_job_id, p_change_tracking_tag, p_date_added
  )
  RETURNING id INTO inserted_id;
  RETURN inserted_id;
END
$function$;

CREATE OR REPLACE FUNCTION public.diff_get_last_scrape_v7(
  i_team_id uuid,
  i_url text,
  i_tag text
)
RETURNS TABLE (o_job_id text, o_date_added timestamptz)
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $function$
  SELECT ct.job_id, ct.date_added
  FROM public.firecrawl_change_tracking_scrapes ct
  WHERE ct.team_id = i_team_id
    AND ct.url = i_url
    AND ct.change_tracking_tag IS NOT DISTINCT FROM i_tag
  ORDER BY ct.date_added DESC
  LIMIT 1
$function$;

CREATE OR REPLACE FUNCTION public.get_zdr_cleanup_batch_2(p_limit integer)
RETURNS TABLE (request_id uuid, ids uuid[])
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $function$
  SELECT NULL::uuid, ARRAY[]::uuid[]
  WHERE false
$function$;

CREATE OR REPLACE FUNCTION public.monitoring_claim_due_monitors(
  p_worker_id text,
  p_limit integer,
  p_lease_seconds integer
)
RETURNS SETOF public.monitors
LANGUAGE plpgsql
VOLATILE
SET search_path = public, pg_temp
AS $function$
BEGIN
  RETURN QUERY
  WITH due AS (
    SELECT m.id
    FROM public.monitors m
    WHERE m.status = 'active'
      AND m.deleted_at IS NULL
      AND m.next_run_at IS NOT NULL
      AND m.next_run_at <= now()
      AND (m.locked_until IS NULL OR m.locked_until < now())
    ORDER BY m.next_run_at
    FOR UPDATE SKIP LOCKED
    LIMIT GREATEST(p_limit, 0)
  )
  UPDATE public.monitors m
  SET locked_at = now(),
      locked_until = now() + make_interval(secs => GREATEST(p_lease_seconds, 1)),
      updated_at = now()
  FROM due
  WHERE m.id = due.id
  RETURNING m.*;
END
$function$;

CREATE OR REPLACE FUNCTION public.get_agent_free_requests_left(i_team_id uuid)
RETURNS TABLE (free_requests_left integer)
LANGUAGE sql
STABLE
AS $function$
  SELECT 2147483647
$function$;

CREATE OR REPLACE FUNCTION public.agent_consume_free_request_if_left(i_team_id uuid)
RETURNS TABLE (consumed boolean)
LANGUAGE sql
VOLATILE
AS $function$
  SELECT true
$function$;
